baseURL = "http://translusion.github.com/"
title = "Translusion"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "© Erik Engheim 2016. All rights reserved."

theme = "minimo"

disqusShortname = "translusion"
googleAnalytics = ""

Paginate = 12
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = false

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Erik Engheim's Projects and Stories"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Erik Engheim"
startYear = "2016"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
# homepage = ["recent_posts"]
#sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
sidebar = ["about"]
footer = ["social_menu"]

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "erik.engheim@mac.com"
github = "ordovician"
linkedin = "erik-engheim-b8831917"
twitter = "erikengheim"
youtube = "UC66PjfTxpg19YCGPUOLzyOg"

[params.comments]
enable = true



# [params.search]
# client = "fuse" # algolia / fuse / lunr
#
# [params.search.algolia]
# appId = ""
# indexName = ""
# searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
    page = "/:filename/"

[[menu.main]]
    name = "Repo"
    weight = 310
    identifier = "repository"
    url = "https://github.com/ordovician"

[[menu.main]]
    name = "Papers"
    weight = 330
    identifier = "papers"
    url = "https://nextjournal.com/erik-engheim"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/posts/"
    weight = 10

# [[menu.main]]
#     name = "Articles"
#     identifier = "articles"
#     url = "/articles/"
#     weight = 15

[[menu.main]]
    name = "Stories"
    identifier = "stories"
    url = "/stories/"
    weight = 16

[[menu.main]]
    name = "Apps"
    identifier = "apps"
    url = "/apps/"
    weight = 40
    
[[menu.main]]
    name = "Maker"
    identifier = "maker"
    url = "/maker/"
    weight = 30

[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/projects/"
    weight = 50
    
[[menu.main]]
    name = "Favorites"
    identifier = "favorites"
    url = "/favorites/"
    weight = 600

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
